// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnkklyastdrylizjucya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBua2tseWFzdGRyeWxpemp1Y3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTU1MzUsImV4cCI6MjA2OTI3MTUzNX0.fNxqvhTIVtmN3cQ3_mmwzQ-L48gZuPcylNyg_-_ID8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});